language: python

services:
  - docker

cache:
  directories:
    - /tmp/travis-cache

before_cache:
  - sudo rm -rf /tmp/travis-cache/root/.cache/pip/http

# https://zato.io/docs/admin/guide/install/index.html#operating-system-considerations
env:
  jobs:
    - MODE=packaging IMAGE=centos:7 PY_BINARY=python3
    - MODE=packaging IMAGE=centos:8 PY_BINARY=python3
    - MODE=packaging IMAGE=ubuntu:18.04 PY_BINARY=python3
    - MODE=packaging IMAGE=ubuntu:20.04 PY_BINARY=python3
    - MODE=packaging IMAGE=debian:9 PY_BINARY=python3
    - MODE=packaging IMAGE=debian:10 PY_BINARY=python3

sudo: required

os:
  - linux
# Use Ubuntu Xenial
dist: xenial

before_install:
  - sudo apt-get update

matrix:
  allow_failures:
    os: osx

notifications:
  email: false

script:
  - source .travis/test_${MODE}.sh

before_cache:
  - sudo rm -rf /tmp/travis-cache/root/.cache/pip/http
