apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zato.postgresql.fullname" . }}
  labels:
    {{- include "zato.postgresql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgresql.replicaCount }}
  selector:
    matchLabels:
      {{- include "zato.postgresql.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zato.postgresql.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "zato.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.postgresql.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.postgresql.fullname }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.postgresql.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          ports:
            - name: {{ .Values.postgresql.fullname }}
              containerPort: {{ default 5432 .Values.odb_port }}
              protocol: TCP
          env:
            {{- toYaml .Values.postgresql.env | nindent 12 }}
          resources:
            {{- toYaml .Values.postgresql.resources | nindent 12 }}
      {{- with .Values.postgresql.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.postgresql.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.postgresql.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zato.redis.fullname" . }}
  labels:
    {{- include "zato.redis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      {{- include "zato.redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zato.redis.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "zato.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.redis.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.redis.fullname }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.redis.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          ports:
            - name: redis
              containerPort: {{ default 6379 .Values.redis_port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
      {{- with .Values.redis.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.redis.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.redis.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zato.zatoscheduler.fullname" . }}
  labels:
    {{- include "zato.zatoscheduler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.zatoscheduler.replicaCount }}
  selector:
    matchLabels:
      {{- include "zato.zatoscheduler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zato.zatoscheduler.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "zato.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.zatoscheduler.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.zatoscheduler.fullname }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: postgres
              containerPort: {{ default 5432 .Values.odb_port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.zatoscheduler.resources | nindent 12 }}
      {{- with .Values.zatoscheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.zatoscheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.zatoscheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zato.zatobootstrap.fullname" . }}
  labels:
    {{- include "zato.zatobootstrap.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.zatobootstrap.replicaCount }}
  selector:
    matchLabels:
      {{- include "zato.zatobootstrap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zato.zatobootstrap.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "zato.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.zatobootstrap.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.zatobootstrap.fullname }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.zatobootstrap.resources | nindent 12 }}
      {{- with .Values.zatobootstrap.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.zatobootstrap.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.zatobootstrap.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zato.zatowebadmin.fullname" . }}
  labels:
    {{- include "zato.zatowebadmin.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.zatowebadmin.replicaCount }}
  selector:
    matchLabels:
      {{- include "zato.zatowebadmin.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zato.zatowebadmin.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "zato.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.zatowebadmin.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.zatowebadmin.fullname }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ default "web" .Values.zatowebadmin.service.name }}
              containerPort: {{ default 8183 .Values.zatowebadmin.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.zatowebadmin.resources | nindent 12 }}
      {{- with .Values.zatowebadmin.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.zatowebadmin.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.zatowebadmin.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zato.zatoserver.fullname" . }}
  labels:
    {{- include "zato.zatoserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.zatoserver.replicaCount }}
  selector:
    matchLabels:
      {{- include "zato.zatoserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zato.zatoserver.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "zato.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.zatoserver.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.zatoserver.fullname }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ default "server" .Values.zatoserver.service.name }}
              containerPort: {{ default 17010 .Values.zatoserver.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.zatoserver.resources | nindent 12 }}
      {{- with .Values.zatoserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.zatoserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.zatoserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
