apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  secretKey: {{ .Values.secretKey | b64enc }}
  jwtSecretKey: {{ .Values.jwtSecretKey | b64enc }}
  zatoWebAdminPassword: {{ .Values.zatoWebAdminPassword | b64enc }}
  zatoIdePublisherPassword: {{ .Values.zatoIdePublisherPassword | b64enc }}
  zatoAdminInvokePassword: {{ .Values.zatoAdminInvokePassword | b64enc }}
  odbPassword: {{ .Values.odbPassword | b64enc }}
