apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  secretKey: {{ required "A valid secretKey is required!" .Values.secretKey | b64enc }}
  jwtSecretKey: {{ required "A valid jwtSecretKey is required!" .Values.jwt_secretKey | b64enc }}
  zatoWebAdminPassword: {{ required "A valid zatoWebAdminPassword is required!" .Values.zatoWebAdminPassword | b64enc }}
  zatoIdePublisherPassword: {{ .Values.zatoIdePublisherPassword | b64enc }}
  zatoAdminInvokePassword: {{ .Values.zatoAdminInvokePassword | b64enc }}
  odbPassword: {{ .Values.odbPassword | b64enc }}
