apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  secretKey: {{ .Values.secretKey | b64enc }}
  jwtSecretKey: {{ .Values.jwtSecretKey | b64enc }}
  {{ if .Values.zatoWebAdminPassword }}zatoWebAdminPassword: {{ .Values.zatoWebAdminPassword | b64enc }}{{- end }}
  {{ if .Values.zatoIdePublisherPassword }}zatoIdePublisherPassword: {{ .Values.zatoIdePublisherPassword | b64enc }}{{- end }}
  {{ if .Values.zatoAdminInvokePassword }}zatoAdminInvokePassword: {{ .Values.zatoAdminInvokePassword | b64enc }}{{- end }}
  odbPassword: {{ .Values.odbPassword | b64enc }}
