# Default values for  zatohelm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
image:
  repository: registry.gitlab.com/zatosource/docker-registry/cloud
  pullPolicy: Always

# Zato's secret variables:
secretKey: ""
jwtSecretKey: ""
zatoWebAdminPassword: ""
zatoIdePublisherPassword: ""
zatoAdminInvokePassword: ""
odbPassword: ""
redisPassword: ""

# Zato's customization variables:
lbPort: "80"
lbAgentPort: "20151"
clusterName: "zato"
redisHostname: ""
redisPort: 6379
odbType: "postgresql"
odbHostname: ""
odbPort: 5432
odbName: "zato"
odbUsername: "zato"
zatoEnmasseFile: ""

global:
  postgresql:
    enabled: true
    replicaCount: 1
    fullname: postgres
    image:
      repository: postgres
      pullPolicy: IfNotPresent
    selectorLabels:
      app: postgres
    podSecurityContext: {}
      # fsGroup: 2000
    securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000
    service:
      type: LoadBalancer
    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}

  redis:
    enabled: true
    replicaCount: 1
    fullname: redis
    image:
      repository: redis
      pullPolicy: IfNotPresent
    selectorLabels:
      app: redis
    podSecurityContext: {}
      # fsGroup: 2000
    securityContext: {}
      # capabilities:
      #   drop:
      #   - ALL
      # readOnlyRootFilesystem: true
      # runAsNonRoot: true
      # runAsUser: 1000
    service:
      type: LoadBalancer
      port: 6379
    resources: {}
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: zatoserviceaccount

zatoscheduler:
  replicaCount: 1
  fullname: scheduler
  replicaCount: 1
  selectorLabels:
      app: scheduler
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  env:
    - name: ZATO_POSITION
      value: "scheduler"

zatobootstrap:
  replicaCount: 1
  fullname: bootstrap
  replicaCount: 1
  selectorLabels:
      app: bootstrap
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

zatowebadmin:
  deploymentKind: "Deployment" # Deployment/StatefulSet
  replicaCount: 1
  fullname: webadmin
  replicaCount: 1
  selectorLabels:
      app: webadmin
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  service:
    name: web
    type: LoadBalancer
    port: 8183
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

  livenessProbe:
    initialDelaySeconds: 150
    failureThreshold: 10
    periodSeconds: 20
  readinessProbe:
    initialDelaySeconds: 110
    failureThreshold: 2
    periodSeconds: 5
  startupProbe:
    initialDelaySeconds: 90
    failureThreshold: 2
    periodSeconds: 30

zatoserver:
  deploymentKind: "Deployment" # Deployment/StatefulSet
  replicaCount: 1
  fullname: server
  replicaCount: 1
  selectorLabels:
      app: server
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  service:
    name: server
    type: LoadBalancer
    port: 17010
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
  volumes:
    # - name: hotdeploy
    #   # volumeMounts information
    #   mount:
    #     name: hotdeploy
    #     mountPath: /opt/hot-deploy
    #   # volumes information
    #   volume:
    #     name: hotdeploy
    #     # Example: Using hostPath volume for hot-deploy.
    #     hostPath:
    #       path: /hotdeploy/
    #       type: Directory
  livenessProbe:
    initialDelaySeconds: 90
    failureThreshold: 10
    periodSeconds: 20
  readinessProbe:
    initialDelaySeconds: 70
    failureThreshold: 2
    periodSeconds: 5
  startupProbe:
    initialDelaySeconds: 60
    failureThreshold: 2
    periodSeconds: 30

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: zato.minikube.local
      paths:
          - /
  # tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
