{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zato.serviceAccountName" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    {{- include "zato.redis.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    checksum/config: {{ printf "%s%s%s%s" (print $.Template.BasePath "/deployment.yaml") (print $.Template.BasePath "/service.yaml") (print $.Template.BasePath "/../values.yaml") (print $.Template.BasePath "/../Chart.yaml") | sha256sum | quote }}
  {{- end }}
{{- end -}}
